name: production-calc
version: 0.1.0.0
github: "Gipphe/production-calc"
license: BSD3
author: "Gipphe"
copyright: "2023 Gipphe"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/githubuser/production-calc#readme>

dependencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
      - hiding (Prelude)
  - aeson
  - aeson-pretty
  - cleff
  - containers
  - directory
  - filepath
  - ixset-typed
  - optparse-applicative
  - relude
  - text

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -Wno-unused-packages

language: GHC2021

default-extensions:
  - DataKinds
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - StrictData
  - TypeFamilies

library:
  source-dirs: src

executables:
  production-calc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - production-calc

tests:
  production-calc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - production-calc
